### ISSUE TITLE
a bug 

### ISSUE THREAD

**Issue by xyq-cyber** [HUST-NingKang-Lab/MGM#1]
1.
使用python程序安装，在安装过程中，transformer安装的版本过高（不止transformer)，会出现和其他python库不兼容的问题，需要单独重新安装低版本的transformer
<img width="857" alt="222" src="https://github.com/HUST-NingKang-Lab/MGM/assets/174620866/29688495-5ee4-45a2-9cce-42b19f8908ba">
2.
在使用pip直接在conda虚拟环境中安装mgm后，各个包版本之间没有冲突（看了一眼，好像requirments里面库的版本安装的都是符合要求的最低版本？），第一步construct可以正常进行，但是pretrain步骤出现报错.
<img width="1273" alt="微信图片_20240703213704" src="https://github.com/HUST-NingKang-Lab/MGM/assets/174620866/d527d559-ab45-47c2-ad4b-5fd58925115c">

**Comment by LudensZhang** [comment]
这是由于高版本的transformer库导致的bug，在最新的版本中我们解决了这一问题，你可以通过pip install microformer-mgm==0.5.5安装更新后的mgm
